"""added jobs table

Revision ID: 48175867460a
Revises: aeeae5949250
Create Date: 2026-01-13 20:25:22.572154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48175867460a'
down_revision = 'aeeae5949250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('resume')

    # ### end Alembic commands ###
