"""initial

Revision ID: aeeae5949250
Revises: 
Create Date: 2026-01-13 17:17:06.007505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeeae5949250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('apply', sa.Integer(), nullable=False),
    sa.Column('shortlist', sa.Integer(), nullable=False),
    sa.Column('interview', sa.Integer(), nullable=False),
    sa.Column('reject', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('linkdin', sa.String(length=20), nullable=True),
    sa.Column('visit', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('desc', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
